### ISSUE TITLE
Too strict version bounds on ghc-events

### ISSUE THREAD

**Issue by sternenseemann** [haskell/ThreadScope#118]
ThreadScope restricts ghc-events to >=0.13 && <0.16, but also compiles with >= 0.16. This should be relaxed, so installing from hackage is possible again.

**Comment by maralorn** [comment]
Tested today, it also works with ghc-events 0.18

**Comment by Mikolaj** [comment]
I see the bound now is `>=0.13 && <0.18`. I can revise the bound on Hackage. @maoe: does it sound like a good idea?

**Comment by Mikolaj** [comment]
If there are no objections in a couple of days I'm going to do this.

**Comment by maoe** [comment]
@Mikolaj Sorry for the delay. I don't have much time to spend for OSS projects recently. Could you or anyone who has permissions please take care of issues/PRs?

**Comment by maralorn** [comment]
@Mikolaj It looks alright now. Thank you.

**Comment by Mikolaj** [comment]
Good to know. Cheers!

**Comment by TeofilC** [comment]
It sounds like this has been resolved. I will close the issue, but please reopen if this is still a problem
