### ISSUE TITLE
Import error in Events.EventDuration

### ISSUE THREAD

**Issue by Kleidukos** [haskell/ThreadScope#127]
Whilst trying to import a rather large eventlog (https://glitchbra.in/flora-cli.eventlog), I get this message and nothing more:

```
findRunThreadTime for Event {evTime = 54752927, evSpec = RunThread {thread = 16917}, evCap = Just 0}
CallStack (from HasCallStack):
  error, called at ./Events/EventDuration.hs:100:42 in main:Events.EventDuration
```

This is rather surprising, as `eventlog2html` is perfectly able to produce this visualisation: https://glitchbra.in/flora-cli.eventlog.html

**Comment by TeofilC** [comment]
Are you still running into this @Kleidukos ?

**Comment by Kleidukos** [comment]
@TeofilC It seems that building from HEAD fixes the problem on new traces. That being said the UI only half-adapts to system themes so there is a mix of light theme background **and** light fonts which make some things unreadable. But that's a different issue.
