### ISSUE TITLE
Feature Request: Retina Text on OS X

### ISSUE THREAD

**Issue by MaxGabriel** [haskell/ThreadScope#34]
Supporting the Retina Display on OS X would really improve the look of ThreadScope. I've never developed with GTK before, but its possible to enable retina text by adding the following to the Info.plist file that goes inside `Threadscope.app` bundle:

``` xml
<key>NSHighResolutionCapable</key>
<true/>
```

Here's a comparison of non-retina vs retina, using this technique (you may need to open these images up in a new window to see how blurry it looks currently):

![screen shot 2014-05-18 at 2 54 11 pm](https://cloud.githubusercontent.com/assets/1274145/3008903/22397a84-ded7-11e3-844d-bdcff9cd8e6a.png)

![screen shot 2014-05-18 at 2 54 50 pm](https://cloud.githubusercontent.com/assets/1274145/3008904/262ef63c-ded7-11e3-992a-2590225b1a87.png)

I'm not sure if its intentional or not, but enabling retina text seems to have really cleaned up the interface as well by removing some visually-cluttering lines.

**Comment by maoe** [comment]
It's a 3 year old ticket but I think this has been resolved by using the Quartz backend of GTK+. Homebrew enabled the backend by default and I see clear text on Retina MBP.

Feel free to reopen if you still have the issue.
