### ISSUE TITLE
Minor compilation issues with recent cairo

### ISSUE THREAD

**Issue by peti** [haskell/ThreadScope#41]
Hi, we've tried to update cairo and several other related packages in NixOS, but these updates break the build of threadscope: http://hydra.cryp.to/build/256390/nixlog/1/raw. This seems like a trivial issue to fix, so I was wondering if, by any chance, you could release a new version to Hackage that fixes these errors?

**Comment by lukerandall** [comment]
@peti can this issue be closed?
