### ISSUE TITLE
ghc-events doesn't compile with ghc 7.10.1RC2

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/ThreadScope#47]
[2 of 8] Compiling GHC.RTS.EventParserUtils ( GHC/RTS/EventParserUtils.hs, dist/build/GHC/RTS/EventParserUtils.o )

GHC/RTS/EventParserUtils.hs:128:5:
    Non type-variable argument in the constraint: MonadError [Char] m
    (Use FlexibleContexts to permit this)
    When checking that ‘undeclared_etype’ has the inferred type
      undeclared_etype :: forall (m :: * -> *) a a1.
                          (Show a1, MonadError [Char] m) =>
                          a1 -> m a
    In an equation for ‘mkEventTypeParsers’:
        mkEventTypeParsers etypes event_parsers
          = accumArray
              (flip const)
              undefined
              (0, max_event_num)
              [(num, parser num) | num <- [0 .. max_event_num]]
          where
              max_event_num = maximum (M.keys etypes)
              undeclared_etype num
                = throwError ("undeclared event type: " ++ show num)
              parser_map = makeParserMap event_parsers
              parser num
                = let ...
                  in
                    case mb_mb_et_size of {
                      Just mb_et_size -> ...
                      Nothing -> ... }

**Comment by Mikolaj** [comment]
Thank you for the report. I guess we'll get to it when @kvelicka merges https://github.com/haskell/ghc-events/pull/4, which seems bound to happen before 7.10.1 is out.

**Comment by GeorgeCo** [comment]
ghc 7.10.1 is out and the issue still exists. Thanks

**Comment by Mikolaj** [comment]
Indeed, I was wrong. Thank you for the reminder. Fixed on branch master. @kvelicka, the fix was very small, so I hope it won't conflict with your changes (unlike the previous commits, regrettably).

**Comment by GeorgeCo** [comment]
Thanks for the quick response!
