### ISSUE TITLE
can't install threadscope on ghc 7.10.1, ghc-events fails to compile

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/ThreadScope#51]
can't install threadscope on ghc 7.10.1 because ghc-events fails to compile

ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.1
bash-3.2$ cabal install threadscope
Resolving dependencies...
Configuring ghc-events-0.4.3.0...
Building ghc-events-0.4.3.0...
Failed to install ghc-events-0.4.3.0
Build log ( /Users/gcolpitts/.cabal/logs/ghc-events-0.4.3.0.log ):
Configuring ghc-events-0.4.3.0...
Building ghc-events-0.4.3.0...
Preprocessing library ghc-events-0.4.3.0...
[1 of 8] Compiling GHC.RTS.EventTypes ( GHC/RTS/EventTypes.hs, dist/build/GHC/RTS/EventTypes.o )
[2 of 8] Compiling GHC.RTS.EventParserUtils ( GHC/RTS/EventParserUtils.hs, dist/build/GHC/RTS/EventParserUtils.o )

GHC/RTS/EventParserUtils.hs:128:5:
    Non type-variable argument in the constraint: MonadError [Char] m
    (Use FlexibleContexts to permit this)
    When checking that ‘undeclared_etype’ has the inferred type
      undeclared_etype :: forall (m :: * -> *) a a1.
                          (Show a1, MonadError [Char] m) =>
                          a1 -> m a
    In an equation for ‘mkEventTypeParsers’:
        mkEventTypeParsers etypes event_parsers
          = accumArray
              (flip const)
              undefined
              (0, max_event_num)
              [(num, parser num) | num <- [0 .. max_event_num]]
          where
              max_event_num = maximum (M.keys etypes)
              undeclared_etype num
                = throwError ("undeclared event type: " ++ show num)
              parser_map = makeParserMap event_parsers
              parser num
                = let ...
                  in
                    case mb_mb_et_size of {
                      Just mb_et_size -> ...
                      Nothing -> ... }
cabal: Error: some packages failed to install:
ghc-events-0.4.3.0 failed during the building phase. The exception was:
ExitFailure 1
threadscope-0.2.6 depends on ghc-events-0.4.3.0 which failed to install.

**Comment by Mikolaj** [comment]
Yes, I'm afraid you need to install ghc-events from the github repo, branch master.

**Comment by GeorgeCo** [comment]
Thanks for the quick response. Glad there is a workaround. I assume this will eventually be fixed so it can be installed via cabal install. Do we have an ETA for that?

**Comment by Mikolaj** [comment]
@simonmar: Given that the fate of 7.10 is decided and it seems to work, it seems stable, etc., would you want to release a new version of ghc-events and TS now?

**Comment by Mikolaj** [comment]
Here are the Hackage package candidates:

http://hackage.haskell.org/package/ghc-events-0.4.4.0/candidate

http://hackage.haskell.org/package/threadscope-0.2.7/candidate

**Comment by Mikolaj** [comment]
Published. Thank you for the report. Closing.

**Comment by GeorgeCo** [comment]
Great! Just installed
Given recent mail on space usage of compiling it is interesting to not that
max resident size was about 800 mb

 /usr/bin/time -l cabal install -j3 threadscope
/usr/bin/time -l cabal install -j3 threadscope
Resolving dependencies...
Downloading ghc-events-0.4.4.0...
Configuring ghc-events-0.4.4.0...
Building ghc-events-0.4.4.0...
Installed ghc-events-0.4.4.0
Downloading threadscope-0.2.7...
Configuring threadscope-0.2.7...
Building threadscope-0.2.7...
Installed threadscope-0.2.7
Updating documentation index
/Users/gcolpitts/Library/Haskell/share/doc/x86_64-osx-ghc-7.10.1/index.html
      179.92 real       136.42 user         7.35 sys
 838103040  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
   1739008  page reclaims
     46278  page faults
         0  swaps
       913  block input operations
       551  block output operations
        25  messages sent
        65  messages received
     17159  signals received
      4160  voluntary context switches
     19345  involuntary context switches

**Comment by Mikolaj** [comment]
Thank you for the feedback. Can't comment on the resident size, but any data points about OSX are very appreciated (even just that it compiles).

**Comment by GeorgeCo** [comment]
Not only does it compile on OS X, it passes a smoke test for running as

threadscope --test ch8

seems to work!

**Comment by GeorgeCo** [comment]
actually there may be some runtime issues

in the bottom pane for Mutator time, GC time and Productivity , all say
(Unavailable). There is no output on HEC 0 etc.

Is this expected? Should I file a bug?

**Comment by Mikolaj** [comment]
That's normal if the eventlog was not generated with extra options (or GHC or ghc-events may be broken). Could you try the one at https://github.com/Mikolaj/eventlogs/blob/master/perf/blackscholes.total.eventlog? It should have all the extra info, including even the spark sizes histogram (quite trivial in this case).
