### ISSUE TITLE
Binaries are outdated in the HaskellWiki

### ISSUE THREAD

**Issue by bruno-cadorette** [haskell/ThreadScope#52]
It would be nice to be able to download the latest version of the program

https://wiki.haskell.org/ThreadScope#Binary_releases

**Comment by Mikolaj** [comment]
Github releases mechanism is not a bad one for binaries. It seems I have sufficient access rights to update the github releases page and redirect the wiki link to release_latest, if somebody volunteers to prepare the binaries.

**Comment by varosi** [comment]
I give +1 for x64 Windows build, because little bit larger profiles cannot be seen on x86 build.

**Comment by varosi** [comment]
+1 even for x86 Windows builds of latest 2.7 version.

**Comment by tmcgilchrist** [comment]
+1 for having pre-built binaries. 

I've poured hours into trying to get this building under OSX with little success.

**Comment by varosi** [comment]
Here I have built 0.2.7 x64 with GHC 8.0.2 against LTS-8.9: https://drive.google.com/file/d/0B7E9nsYnaKCcQnBNUUlXcU9sRFE/view?usp=sharing

If someone could check if everything is in-place and upload it to the Wiki it will be cool.

**Comment by varosi** [comment]
master branch is incompatible with latest LTS-8.9, because of ghc-events 0.5 dependency which is not in LTS, yet.

**Comment by varosi** [comment]
hm, there is a problem with finding .ui file on another machine. So I have to find where to tell it to search it.

**Comment by varosi** [comment]
Problem is fixed. You could find binary distributable here:
https://drive.google.com/open?id=0B7E9nsYnaKCcQnBNUUlXcU9sRFE

**Comment by varosi** [comment]
hm, is that project dead? No one answer here.

**Comment by Mikolaj** [comment]
@varosi: I'm sorry, I missed your first ping. No, the project is not dead; it just has a very busy maintainer (@simonmar). As soon as I'm able to run this binary under `wine` (or one of the contributors with a Windows machine manages to run it and/or scan for viruses) I will somehow publish it. Thank you and I apologize again for ignoring you. :)

**Comment by Mikolaj** [comment]
Yay, it runs under `wine` (from the `bin/` directory). I've uploaded it to https://github.com/haskell/ThreadScope/releases and linked from https://wiki.haskell.org/ThreadScope#Binary_releases  https://github.com/haskell/ThreadScope/releases. Thanks again!

We are still waiting for OS X binaries, though...

**Comment by varosi** [comment]
I have pushed pull request about how it could be builded easily under Windows with Stack, too.

**Comment by varosi** [comment]
I don't see it at https://wiki.haskell.org/ThreadScope#Binary_releases

**Comment by Mikolaj** [comment]
Yes, I left the old link, but I mentioned it's old and pointed to the new location. If you have suggestions re wordking, please share.

The PR looks very handy. I'm sure the maintainer will incorporate all or potions of it next time a release is prepared.

**Comment by varosi** [comment]
Ah, okay. I didn't saw this text under 0.2.2 builds. Great, thanks!

**Comment by maoe** [comment]
We've set up GitHub Releases. Binaries are uploaded there on every tag.

**Comment by varosi** [comment]
Isn't it good if 0.2.2 builds are removed as links from the [Wiki site,](https://wiki.haskell.org/ThreadScope#Binary_releases) because on the first sight people don't see that there is a link to newer ones beneath it?

**Comment by Mikolaj** [comment]
@varosi: right, edited it out. :)
