### ISSUE TITLE
ThreadScope core dumps when linked with threaded runtime

### ISSUE THREAD

**Issue by TerrorJack** [haskell/ThreadScope#53]
When linked with threaded runtime (cabal install --ghc-options="-threaded" threadscope), ThreadScope can start normally, but core dumps when clicked on the "open" button. The error message is simply "Segmentation fault (core dump)".

The version of threadscope is 0.2.7, compiled by ghc 7.10.2 on 64-bit Linux.

**Comment by Mikolaj** [comment]
Yes, that's a known issue (or feature): 

https://github.com/haskell/ThreadScope/blob/master/threadscope.cabal#L89 

gtk2hs is used in TS in a very simple and safe way that conflicts with -threaded. I guess, with current gtk2hs versions, the TS code could be rewritten to accept -threaded, but I doubt it's worth the risk of introducing errors (some very subtle, some possibly outside of TS itself).

**Comment by TerrorJack** [comment]
@Mikolaj Thank you. This issue isn't bothering me, since TS doesn't use SMP parallelism; but it would be nice if you put a short notice on hackage & haskell wiki to prevent people from using -threaded.

**Comment by Mikolaj** [comment]
Couid you do it? I would help, if needed.

**Comment by simonmar** [comment]
Strange, I thought I had this working in the past.  What's the issue?
