### ISSUE TITLE
Threadscope fails to read partially written file

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/ThreadScope#6]
**Original reporter**: _manpacket@<hidden>_

If ghc compiled program was launched with option to write eventlog and then was interrupted by Ctrl-C then eventlog file will be partially written.

Actual behaviour: Threadscope fails to read such file complaining "There was a problem loading the eventlog", "too few bytes. Failed reading at byte position 4194995"

Expecting behaviour: threadscope displays an info box saying that file was damaged and only first XXXX bytes (YYY seconds) was recovered then it should work as if this file was finalized properly.

**Comment by maoe** [comment]
I believe this is fixed in ghc-events and thus in v0.2.8 of threadscope.
