### ISSUE TITLE
Include README.md in the cabal file

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/ThreadScope#72]
I struggled with installing threadscope on Mac OS X. First of all my macports had gtk-x11 installed by default, it was not clear that I had to install the quartz variant. I somehow figured that and installed the quartz variant, but the gtk-mac-integration package still showed compilation errors. From the README at this github project page I figured that the following flag was to be used:

```
stack install --flag gtk:have-quartz-gtk
```

This worked. I could have saved a lot of time if the README was included on the hackage page. Please include it in the cabal so that it can be shown on hackage.

**Comment by maoe** [comment]
Thanks for your report. Apparently I forgo to update the cabal file when I added the README.

Would you mind updating it? Or I can do it probably later today.

**Comment by maoe** [comment]
Also I managed to set up binary release via GitHub Releases on [my fork](https://github.com/maoe/ThreadScope/commit/4def28fa6af3679e4789cfd538f2bcb8d7c69b81). It'd be great if you could check that the [the binary on the release page](https://github.com/maoe/ThreadScope/releases/tag/test-release-5) works on your machine.

**Comment by maoe** [comment]
Updated the cabal file on master.
