### ISSUE TITLE
instructions for installing threadscope on mac os from source don't seem to work

### ISSUE THREAD

**Issue by GeorgeCo** [haskell/ThreadScope#83]
from https://hackage.haskell.org/package/threadscope:

Building from source
...
Then you can build threadscope using cabal:

cabal new-build --constraint="gtk +have-quartz-gtk"

but when I try that I get

 cabal new-build --constraint="gtk +have-quartz-gtk" threadscope
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.

bash-3.2$

**Comment by Mikolaj** [comment]
Oh, indeed, I see here

https://github.com/haskell/ThreadScope/blob/master/.travis.yml

that cabal.project is auto-generated. Does it work for you, if you generate similarly?

@maoe: what do we do about this discrepancy?

**Comment by maoe** [comment]
Hmm I don't think `cabal.project` is necessary to build because there exists the `threadscope.cabal` at the project root directory.

@GeorgeCo Were you at the project root directory when you got that error? Also what version of cabal-install do you use?

**Comment by maoe** [comment]
Ah I think I know what happened. I guess you ran that command outside the source repository. I guessed so because you passed `threadscope` at the end of the command line.

[`cabal new-build`](http://cabal.readthedocs.io/en/latest/nix-local-build.html#cabal-new-build) is, unlike `stack install`, used to build stuff in a source repository. If you'd like to install a package without the source code there is [`cabal new-install`](http://cabal.readthedocs.io/en/latest/nix-local-build.html#cabal-new-install).

**Comment by GeorgeCo** [comment]
Thanks for taking the time to look at this. Good observation! I was actually just trying to follow the instructions but mistakenly added threadscope on the end. As you suggest, that is because I normally do cabal install

Back to following instructions, I don't see anything at https://hackage.haskell.org/package/threadscope that would put me in the source repository. Nor do I see anything about the project root directory.

The instructions on the page say

> Building from source
> ...
> OS X
> GTK+ and gtk-mac-integration are required.
> 
> brew install gtk+ gtk-mac-integration
> Then you can build threadscope using cabal:
> 
> cabal new-build --constraint="gtk +have-quartz-gtk"

There is nothing on the page about getting the source repository or the project root directory. Am I missing something or are the instructions missing something? 

When I do 

> cabal new-build --constraint="gtk +have-quartz-gtk"

I get

> No cabal.project file or cabal file matching the default glob './*.cabal' was found.
> Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.

FWIW, when I do

 

> cabal new-install -j5 --constraint="gtk +have-quartz-gtk" threadscope

I get 

> Configuring library for ghc-events-0.4.4.0..
> clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
> Preprocessing library for ghc-events-0.4.4.0..
> Building library for ghc-events-0.4.4.0..
> ...
> [8 of 8] Compiling GHC.RTS.Events.Merge ( GHC/RTS/Events/Merge.hs, dist/build/GHC/RTS/Events/Merge.o )
> 
> GHC/RTS/Events/Merge.hs:52:10: error:
>     • No instance for (Semigroup MaxVars)
>         arising from the superclasses of an instance declaration
>     • In the instance declaration for ‘Monoid MaxVars’
>    |
> 52 | instance Monoid MaxVars where
>    |          ^^^^^^^^^^^^^^
> cabal: Failed to build ghc-events-0.4.4.0 (which is required by
> threadscope-0.2.7). See the build log above for details.
> 

I am using:

>  ghc --version
> The Glorious Glasgow Haskell Compilation System, version 8.4.2
> bash-3.2$ cabal --version
> cabal-install version 2.2.0.0
> compiled using version 2.2.0.1 of the Cabal library

**Comment by maoe** [comment]
> cabal: Failed to build ghc-events-0.4.4.0 (which is required by
> threadscope-0.2.7). See the build log above for details.

Hmm it's strange that cabal picked such an old version of ghc-events.

> There is nothing on the page about getting the source repository or the project root directory. Am I missing something or are the instructions missing something?

I thought it was obvious. I've updated the instructions in https://github.com/maoe/ThreadScope/commit/05a8c3fdb155db877cc70c5311928058c1f1c715. Does it help?

**Comment by GeorgeCo** [comment]
Thanks yes, however I am using ghc 8.4.3 and the build fails, not sure if you want a new issue for that as it does compile with --allow-new.

I do think it would be good to fix cabal install and cabal new-install as I just wanted to check if threadscope compiled with the latest ghc. I didn't actually need to download the source to my machine but tried that as cabal install did not work. I think the pre-built binaries would be how mist people get threadscope and that worked for me.

**Comment by GeorgeCo** [comment]
sorry, building from source (new-build) failed with ghc 8.4.3. Do you want me to open an issue:

[ 7 of 37] Compiling GUI.BookmarkView ( GUI/BookmarkView.hs, /Users/gcolpitts/haskell/threadscope/threadscope-0.2.10/dist-newstyle/build/x86_64-osx/ghc-8.4.3/threadscope-0.2.10/build/threadscope/threadscope-tmp/GUI/BookmarkView.o )

GUI/BookmarkView.hs:84:39: error:
    • Couldn't match expected type ‘Maybe model0’
                  with actual type ‘ListStore (Timestamp, String)’
    • In the second argument of ‘treeViewSetModel’, namely
        ‘bookmarkStore’
      In a stmt of a 'do' block:
        treeViewSetModel bookmarkTreeView bookmarkStore
      In the expression:
        do let getWidget cast name = builderGetObject builder cast name
           bookmarkTreeView <- getWidget castToTreeView "bookmark_list"
           bookmarkStore <- listStoreNew []
           columnTs <- treeViewColumnNew
           ....
   |
84 |     treeViewSetModel bookmarkTreeView bookmarkStore
   |                                       ^^^^^^^^^^^^^
bash-3.2$

**Comment by maoe** [comment]
There's a new version (v0.2.11) that fixes the issue. Could you try that?

**Comment by GeorgeCo** [comment]
Yep, that works,thanks!
