### ISSUE TITLE
threadscope.exe: user error (Couldn't recognize the image file format for file "...threadscope4118467.png")

### ISSUE THREAD

**Issue by chenyulue** [haskell/ThreadScope#95]
I build and install threadscope-0.2.11.1 with ghc-8.0.2 on windows 10, and it can be builded successfully with `cabal install`. 

However, when I type `threadscope` in powershell, I get a user error:

> threadscope.exe: user error (Couldn't recognize the image file format for file "C:\Users\[UserName]\AppData\Local\Temp\threadscope4118467.png“）

I have installed gtk2hs successfully, so why this problem? Thanks for any tips!

**Comment by Mikolaj** [comment]
Hi! Can you view this image file outside ThreadScope? Can you compile and run successfully on another OS, or run the binary version at https://github.com/haskell/ThreadScope/releases/tag/v0.2.11 ?

**Comment by chenyulue** [comment]
@Mikolaj The fact is the `png` image cannot be found in the metioned directory. Since now only windows 10 is available to me, I have not tried it on another OS.

**Comment by Mikolaj** [comment]
What happens when you copy file `threadscope.png` from source directory to the file you mentioned, creating any directories as needed? Perhaps that would let you use TS while the bug is being investigated. BTW is `threadscope.png` installed anywhere? To which path? Which version of gtk2hs did you install and how?

**Comment by Mikolaj** [comment]
Now that I look at README, it advises to use `cabal new-install` and to install gtk twice. Could you follow he instructions and report back? Thank you.

**Comment by maoe** [comment]
The logo image is embedded into the binary and at runtime it gets written to a temporary file then is read by `pixbufNewFromFile`. See the [relevant code](https://github.com/haskell/ThreadScope/blob/607e113ba2df4a0ca2530459fc4fd6761cc04fb7/GUI/DataFiles.hs#L25-L34).

Could you
* check if there's the png file while ThreadScope is running? It's a temporary file so it's likely to be deleted when the application exits.
* check if the pre-built binary works

Also how did you install gtk2hs?

**Comment by chenyulue** [comment]
@Mikolaj 
I have installed gtk twice, and also copied `threadscope.png` to the temporary directory and renamed it to `threadscope4118467.png` or the current directory where `threadscope` is in, but the same issue remains.

`gtk` was installed by `msys2`, and the haskell package `gtk` is version 0.14.7. `ghc` is 8.0.2, `cabal` is 1.24.0.2, and `threadscope` is installed by `cabal install`. 

I have not tried `cabal new-install`, since cabal-1.24.0.2 does not support `new-install` and I do not have permissions to install and update applications in the company's computer.

So I tried to build `threadscope` on my own computer according to your suggestions, and the compiled app works without any problems. So the issue may be related to my computer's permission limitation. 

However, since you tells me where the `.png` file is needed in the code, I have commented the codes in the two modules `GUI.APP` and `GUI.MainWindow` where the `loadLogo` is used, and changed the  `Just logo` to `Nothing`, and then the compiled `threadscope` works successfully on my company's computer. To this app, the icon is not mandatory.

So the above issue is worked around on my company's computer, and thanks for your help!

**Comment by maoe** [comment]
> I have installed gtk twice, and also copied threadscope.png to the temporary directory and renamed it to threadscope4118467.png or the current directory where threadscope is in, but the same issue remains.

Note that the PNG file is a temporary file that's likely to have a different name each run. Would you mind replacing the `withSystemTempFile logoFile` with `withFile "/some/writable/location.png" WriteMode` and checking if the issue remains?

> So I tried to build threadscope on my own computer according to your suggestions, and the compiled app works without any problems. So the issue may be related to my computer's permission limitation.

Sounds possible. Do you have permissions to write a file in `C:\Users[UserName]\AppData\Local\Temp\`?

> However, since you tells me where the .png file is needed in the code, I have commented the codes in the two modules GUI.APP and GUI.MainWindow where the loadLogo is used, and changed the Just logo to Nothing, and then the compiled threadscope works successfully on my company's computer. To this app, the icon is not mandatory.

Yeah the app should work without the logo. Maybe `$loadLogo` should return `IO (Maybe Pixbuf)` so that the app can continue to work even if it fails to load the logo.

**Comment by maoe** [comment]
A quick search of the error message turned up this link: https://wiki.gnome.org/Projects/Jhbuild/Issues/gtk%2B

It seems that this error message is not uncommon and `gdk-pixbuf-query-loaders` can be used to fix it.

**Comment by maoe** [comment]
> Maybe $loadLogo should return IO (Maybe Pixbuf) so that the app can continue to work even if it fails to load the logo for some reason.

Implemented in https://github.com/haskell/ThreadScope/compare/master...maoe:optional-logo. Could you give it a try on your work computer?

**Comment by chenyulue** [comment]
> Note that the PNG file is a temporary file that's likely to have a different name each run. Would you mind replacing the withSystemTempFile logoFile with withFile "/some/writable/location.png" WriteMode and checking if the issue remains?

I have tried this and the issue remains. Also, I have the permission to write files in the system temporary directory, so the reason should be missing the `gdk-pixbuf loaders cache file` stated in the above link. BTW, how to get the `gdk-pixbuf loaders cache file` on windows? By msys2?

> Implemented in master...maoe:optional-logo. Could you give it a try on your work computer?

It still doesn't work. However, using `SomeException` instead of `IOException` works. Seems missing the cache file is not an exception that occurs in the IO monad.  I have no idea which specific exception it belongs to.

**Comment by maoe** [comment]
Apparently pixbufNewFromFile uses propagateGError, which may throw glib's GError.

**Comment by chenyulue** [comment]
@maoe Then which `Exception` [instance](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Exception.html#t:Exception) should be chosen?

**Comment by maoe** [comment]
It should be GError. I made a fix in the optional-logo branch. Could you fetch and try again?

**Comment by maoe** [comment]
> BTW, how to get the gdk-pixbuf loaders cache file on windows? By msys2?

I'm not familiar with Windows and don't have a machine to test on but I guess it should be available in the MSYS2 shell.

**Comment by chenyulue** [comment]
@maoe With `GError`, it works.

**Comment by maoe** [comment]
Great! Thanks for checking. I’ll make a PR later.

**Comment by Mikolaj** [comment]
You rock, guys. :)
